import Foundation
import MachOKit
import MachOFoundation

public protocol HeapMetadataHeaderProtocol: TypeMetadataLayoutPrefixProtocol, HeapMetadataHeaderPrefixProtocol, TypeMetadataHeaderBaseProtocol where Layout: HeapMetadataHeaderLayout {}
