import Foundation

/// The tool a product says it was generated by.
public struct GeneratorIdentity: Sendable, Hashable {
    public var name: String
    public var version: String

    public init(name: String, version: String) {
        self.name = name
        self.version = version
    }
}

/// What a request stamps into its product without being asked to compute it:
/// who generated it, and when.
///
/// Injected rather than read from the process so that a host stamps its own
/// name, and a test gets the same bytes on every run.
public struct SwiftSectionEnvironment: Sendable {
    /// Stamped into interface headers and snapshot provenance.
    public var generator: GeneratorIdentity
    /// Stamped into snapshot provenance as `createdAt`.
    public var currentDate: @Sendable () -> Date

    public init(generator: GeneratorIdentity, currentDate: @escaping @Sendable () -> Date = { Date() }) {
        self.generator = generator
        self.currentDate = currentDate
    }
}
