package enum XcodeMachOFileName {
    package enum SharedFrameworks: String {
        case AccessibilityAudit
        case AccessibilitySupport
        case AppResourceGeneration
        case AppThinning
        case AssetRuntimeSupport
        case AuthenticationAPI
        case CodeCompletionFoundation
        case CodeCompletionKit
        case CodeGenerationIntelligence
        case CombineXPC
        case CommonXcodeCloudAPI
        case ContentDelivery
        case ContentDeliveryServices
        case CoreDocumentation
        case CoreSymbolicationDT
        case CreateMLSwiftProtobuf
        case DNTDocumentationModel
        case DNTDocumentationSupport
        case DNTSourceKitSupport
        case DNTTransformer
        case DTDeviceKit
        case DTDeviceKitBase
        case DTDeviceServices
        case DTGTGraph
        case DTGTTimeline
        case DTGanache
        case DTGraphKit
        case DTMLOpGraph
        case DTXConnectionServices
        case DVTAnalytics
        case DVTAnalyticsClient
        case DVTAnalyticsKit
        case DVTAnalyticsMetrics
        case DVTAnalyticsMetricsClient
        case DVTAppStoreConnect
        case DVTCocoaAdditionsKit
        case DVTCoreDeviceCore
        case DVTCoreGlyphs
        case DVTCrashLogFoundation
        case DVTDeviceFoundation
        case DVTDeviceKit
        case DVTDeviceProvisioning
        case DVTDocumentation
        case DVTExplorableKit
        case DVTFeedbackReporting
        case DVTFoundation
        case DVTITunesSoftware
        case DVTITunesSoftwareServiceFoundation
        case DVTIconKit
        case DVTInstrumentsAnalysisCore
        case DVTInstrumentsFoundation
        case DVTInstrumentsUtilities
        case DVTKeychain
        case DVTKeychainService
        case DVTKeychainUtilities
        case DVTKit
        case DVTLibraryKit
        case DVTMacroFoundation
        case DVTMarkup
        case DVTPlaygroundCommunication
        case DVTPlaygroundStubMacServices
        case DVTPortal
        case DVTProducts
        case DVTProductsUI
        case DVTServices
        case DVTSmartSearch
        case DVTSourceControl
        case DVTSourceEditor
        case DVTStructuredLayoutKit
        case DVTSystemPrerequisites
        case DVTSystemPrerequisitesUI
        case DVTUserInterfaceKit
        case DVTViewControllerKit
        case DebugHierarchyFoundation
        case DebugHierarchyKit
        case DebugSymbolsDT
        case DeltaFoundation
        case DeltaKit
        case EventsAPI
        case GLTools
        case GLToolsAnalysisEngine
        case GLToolsCore
        case GLToolsExpert
        case GLToolsInterface
        case GLToolsServices
        case GLToolsShaderProfiler
        case GPUTools
        case GPUToolsCore
        case GPUToolsDesktopFoundation
        case GPUToolsMobileFoundation
        case GPUToolsPlatform
        case GPUToolsRenderer
        case GPUToolsServices
        case GPUToolsShaderProfiler
        case GameToolsFoundation
        case HexFiend
        case IDEAnalyticsMetrics
        case IDECodeGenerationIntelligence
        case IDEDistribution
        case IDEDistributionKit
        case IDEMLCompilerCore
        case IDEMLModelCore
        case IDEMLModelEditorKit
        case IDEMLReferenceObjectCompilerCore
        case IDEPlaygroundEditor
        case IDEPlaygroundExecution
        case IDEPlaygroundResultsFoundation
        case IDEPlaygroundResultsKit
        case IDEPlaygroundsFoundation
        case IDEPlaygroundsKit
        case IDEProducts
        case IDEResultKit
        case LLDB
        case LLDBRPC
        case LearnedFeatures
        case LiveExecutionResultsFoundation
        case LiveExecutionResultsHost
        case Localization
        case LoggingSupportHost
        case MLCloudDeployment
        case MLCloudDeploymentXPCServiceProtocol
        case MLCore
        case MLCoreKit
        case MLDataAnnotation
        case MLDataAnnotationKit
        case MLDataSource
        case MLDataSourceKit
        case MLEvaluation
        case MLEvaluationKit
        case MLExperiment
        case MLExplorationKit
        case MLFeature
        case MLModelCore
        case MLModelFormatEditor
        case MLModelKit
        case MLPersistenceEngine
        case MLPersistenceEntity
        case MLRecipeCore
        case MLRecipeExecutionController
        case MLRecipeExecutionServiceProtocol
        case MLShared
        case MLSharedKit
        case MLTraceReport
        case MTLTools
        case MTLToolsAnalysisEngine
        case MTLToolsServices
        case MTLToolsShaderProfiler
        case MallocStackLoggingDT
        case MarkupSupport
        case Notarization
        case ODTDevTool
        case OpenAPIRuntime
        case OpenAPIURLSession
        case PackedPaths
        case PreviewsDeveloperTools
        case PreviewsFoundationHost
        case PreviewsMessagingHost
        case PreviewsModel
        case PreviewsPipeline
        case PreviewsPlatforms
        case PreviewsScenes
        case PreviewsSyntax
        case PreviewsUI
        case PreviewsXROSMessaging
        case PreviewsXROSServices
        case PreviewsXcodeUI
        case RealityKitAdditions
        case RealityKitInspection
        case RealityToolKit
        case RealityToolsDeviceSupport
        case Recount
        case SourceEditor
        case SourceEditorRegExSupport
        case SourceEditorSwiftSupport
        case SourceKit
        case SourceKitSupport
        case SourceModel
        case SourceModelSupport
        case SpatialInspectorFoundation
        case StatusAPI
        case SwiftBasicFormat
        case SwiftBuild
        case SwiftDiagnostics
        case SwiftOperators
        case SwiftPM
        case SwiftParser
        case SwiftParserDiagnostics
        case SwiftRefactor
        case SwiftSyntax
        case SwiftSyntaxBuilder
        case SwiftSyntaxCShims
        case SwiftSyntaxMacroExpansion
        case SwiftSyntaxMacros
        case SwiftSyntaxSupport
        case SwiftUITracingSupportDT
        case SymbolCache
        case SymbolCacheIndexing
        case SymbolCacheSupport
        case SymbolicationDT
        case TestResultsUI
        case Testing
        case USDLib_FormatLoaderProxy_Xcode
        case UVTestSupport
        case XCBuild
        case XCResultKit
        case XCServices
        case XCSourceControl
        case XCStringsParser
        case XCTAutomationSupport
        case XCTDaemonControl
        case XCTDaemonControlMobileDevice
        case XCTHarness
        case XCTest
        case XCTestCore
        case XCTestSupport
        case XCUIAutomation
        case XCUnit
        case XcodeCloudAPI
        case XcodeCloudCombineAPI
        case XcodeCloudDataSource
        case XcodeCloudFoundation
        case XcodeCloudKit
        case XcodeCloudUI
        case _CodeCompletionFoundation
        case kperfdataDT
        case ktraceDT
        case libXCTestSwiftSupport
        case llbuild
        package var pathComponent: String {
            "/SharedFrameworks/\(rawValue).framework"
        }
    }

    case sharedFrameworks(SharedFrameworks)

    package var contentsDirectory: String {
        "/Applications/Xcode.app/Contents"
    }

    package var path: String {
        switch self {
        case .sharedFrameworks(let framework):
            return "\(contentsDirectory)\(framework.pathComponent)"
        }
    }
}
