import MachOKit
import MachOFoundation

public protocol ClassMetadataObjCInteropProtocol: AnyClassMetadataObjCInteropProtocol, FinalClassMetadataProtocol where Layout: ClassMetadataObjCInteropLayout {}

