import Foundation
import Testing
import OutputTransformer
import SwiftOutputTransformer
import SwiftSectionKit

/// `dump` and `interface` against the SymbolTestsCore fixture: which sections
/// are read and how a failure surfaces, where the product goes, and the
/// progress a host hears. What the rendered declarations say is pinned by the
/// snapshot suites; these pin what the requests add around them.
@Suite
struct DumpAndInterfaceRequestTests {
    private static let fixture = MachOSource.file(path: FixtureFiles.symbolTestsCore, architecture: nil)

    /// A plain C tool: a Mach-O with no Swift section at all.
    private static let nonSwiftBinaryPath = "/usr/bin/true"

    // MARK: - dump

    @Test("Every section of the fixture is dumped as it is read, and a file holds exactly what was printed")
    func dumpToOutputAndToFile() async throws {
        let directoryURL = try FixtureFiles.makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directoryURL) }
        let dumpPath = directoryURL.appendingPathComponent("dump.txt").path

        let printed = RecordingOutput()
        try await DumpRequest(source: Self.fixture).run(output: printed, environment: .testing)
        let written = RecordingOutput()
        try await DumpRequest(source: Self.fixture, destination: .file(path: dumpPath)).run(output: written, environment: .testing)

        #expect(printed.printedProduct.contains("@objc(SymbolTestsCoreObjCBridgeClass)"))
        #expect(printed.diagnostics.isEmpty)
        #expect(written.events.isEmpty)
        #expect(try String(contentsOfFile: dumpPath, encoding: .utf8) == printed.printedProduct)
    }

    @Test("A section asked for by name reports what it cannot read; the default selection stays silent", .enabled(if: FileManager.default.fileExists(atPath: nonSwiftBinaryPath)))
    func explicitSectionsReportFailures() async throws {
        let source = MachOSource.file(path: Self.nonSwiftBinaryPath, architecture: .arm64e)

        let explicit = RecordingOutput()
        try await DumpRequest(source: source, sections: .only([.types, .protocols])).run(output: explicit, environment: .testing)
        let errors = explicit.messages(of: .error)
        #expect(errors.count == 2)
        #expect(errors.first?.hasPrefix("Swift section __swift5_types not found") == true)
        #expect(errors.last?.hasPrefix("Swift section __swift5_protos not found") == true)

        let defaulted = RecordingOutput()
        try await DumpRequest(source: source).run(output: defaulted, environment: .testing)
        #expect(defaulted.events.isEmpty)
    }

    @Test("An empty section asked for by name says so in the product")
    func explicitEmptyObjCImplementationSection() async throws {
        let output = RecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.objcImplementationClasses])).run(output: output, environment: .testing)
        #expect(output.printedProduct == "// No @objc @implementation classes recognized in this image.\n")
    }

    @Test("Binary order reorders the declarations, never adds or drops one")
    func binaryOrderKeepsEveryDeclaration() async throws {
        let bySection = RecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.types, .protocols])).run(output: bySection, environment: .testing)
        let inBinaryOrder = RecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.types, .protocols]), ordering: .binaryOrder).run(output: inBinaryOrder, environment: .testing)

        let declarationsBySection = bySection.products.compactMap(Self.declarationText)
        let declarationsInBinaryOrder = inBinaryOrder.products.compactMap(Self.declarationText)
        #expect(!declarationsBySection.isEmpty)
        #expect(declarationsBySection.sorted() == declarationsInBinaryOrder.sorted())
    }

    @Test("The header names the environment's generator")
    func dumpHeaderNamesTheGenerator() async throws {
        let output = RecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.protocols]), emitsHeader: true).run(output: output, environment: .testing)
        #expect(output.printedProduct.hasPrefix("// Generated by swift-section-kit-tests 9.9.9\n"))
    }

    /// Passing a template is enough to see its output; no separate switch for
    /// the comment kind it renders.
    @Test("A comment template turns its comment kind on")
    func commentTemplateEnablesItsCommentKind() async throws {
        var transformers = Transformer.SwiftConfiguration()
        transformers.swiftMemberAddress.isEnabled = true
        transformers.swiftMemberAddress.template = "ADDRESS[${offset}]"

        let withTemplate = RecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.protocolConformances]), commentTransformers: transformers)
            .run(output: withTemplate, environment: .testing)
        let withoutTemplate = RecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.protocolConformances])).run(output: withoutTemplate, environment: .testing)

        #expect(withTemplate.printedProduct.contains("ADDRESS["))
        #expect(!withoutTemplate.printedProduct.contains("ADDRESS["))
    }

    private static func declarationText(_ product: SwiftSectionProduct) -> String? {
        if case .declarations(let semanticString) = product { semanticString.string } else { nil }
    }

    // MARK: - dump: what each piece declares

    @Test("Every declaration a dump prints comes with what it declares, and the pieces are those a plain output gets")
    func everyDeclarationIsNamed() async throws {
        let plain = RecordingOutput()
        try await DumpRequest(source: Self.fixture).run(output: plain, environment: .testing)
        let named = DeclarationRecordingOutput()
        try await DumpRequest(source: Self.fixture).run(output: named, environment: .testing)

        let namedPieces = named.declarationPieces
        #expect(!namedPieces.isEmpty)
        #expect(namedPieces.allSatisfy { $0.declaration != nil })
        #expect(namedPieces.map(\.declarationText) == plain.products.compactMap(Self.declarationText))
    }

    struct TypeAndConformance: Sendable, CustomTestStringConvertible {
        let typeName: String
        let typeLinePrefix: String
        let conformanceLinePrefix: String

        var testDescription: String { typeName }
    }

    /// What a host files one type's pieces together by.
    @Test("A type and its conformances share one name", arguments: [
        TypeAndConformance(
            typeName: "SymbolTestsCore.Enums.NoPayloadEnumTest",
            typeLinePrefix: "enum SymbolTestsCore.Enums.NoPayloadEnumTest {",
            conformanceLinePrefix: "extension SymbolTestsCore.Enums.NoPayloadEnumTest: Swift.Equatable"
        ),
        TypeAndConformance(
            typeName: "SymbolTestsCore.Generics.GenericRequirementTest",
            typeLinePrefix: "struct SymbolTestsCore.Generics.GenericRequirementTest<",
            conformanceLinePrefix: "extension SymbolTestsCore.Generics.GenericRequirementTest: Swift.Equatable"
        ),
    ])
    func typeAndConformancesShareName(_ typeAndConformance: TypeAndConformance) async throws {
        let output = DeclarationRecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.types, .protocolConformances])).run(output: output, environment: .testing)

        #expect(output.declaration(ofPieceStartingWith: typeAndConformance.typeLinePrefix) == .swift(.types, name: typeAndConformance.typeName))
        #expect(output.declaration(ofPieceStartingWith: typeAndConformance.conformanceLinePrefix) == .swift(.protocolConformances, name: typeAndConformance.typeName))
    }

    /// A file-scope private type's name carries the file's discriminator;
    /// its conformance has to be named with it, or a host files the two apart.
    @Test("A file-private type and its conformance share one name")
    func filePrivateTypeAndConformanceShareName() async throws {
        let output = DeclarationRecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.types, .protocolConformances])).run(output: output, environment: .testing)

        let typeNames = output.declarationPieces.compactMap { piece -> String? in
            guard case .swift(.types, let name)? = piece.declaration, name?.contains("AlphaProtocolWitness") == true else { return nil }
            return name
        }
        let conformanceNames = output.declarationPieces.compactMap { piece -> String? in
            guard case .swift(.protocolConformances, let name)? = piece.declaration,
                  piece.declarationText?.contains("PrivateDoppelgangerProtocol") == true,
                  name?.contains("AlphaProtocolWitness") == true
            else { return nil }
            return name
        }
        #expect(typeNames.count == 1)
        #expect(conformanceNames.count == 1)
        #expect(conformanceNames == typeNames)
    }

    @Test("A protocol is named as declared")
    func protocolIsNamed() async throws {
        let output = DeclarationRecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.protocols])).run(output: output, environment: .testing)

        #expect(output.declaration(ofPieceStartingWith: "protocol SymbolTestsCore.Protocols.ProtocolTest ") == .swift(.protocols, name: "SymbolTestsCore.Protocols.ProtocolTest"))
    }

    @Test("An associated type is named after the type that witnesses it")
    func associatedTypeIsNamedAfterItsType() async throws {
        let output = DeclarationRecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.associatedTypes])).run(output: output, environment: .testing)

        #expect(
            output.declaration(ofPieceStartingWith: "extension SymbolTestsCore.Generics.GenericRequirementTest: SymbolTestsCore.Protocols.ProtocolTest")
                == .swift(.associatedTypes, name: "SymbolTestsCore.Generics.GenericRequirementTest")
        )
    }

    @Test("Binary order names the same declarations")
    func binaryOrderNamesTheSameDeclarations() async throws {
        let bySection = DeclarationRecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.types, .protocols])).run(output: bySection, environment: .testing)
        let inBinaryOrder = DeclarationRecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.types, .protocols]), ordering: .binaryOrder).run(output: inBinaryOrder, environment: .testing)

        let bySectionDeclarations = Set(bySection.declarationPieces.compactMap(\.declaration))
        #expect(!bySectionDeclarations.isEmpty)
        #expect(Set(inBinaryOrder.declarationPieces.compactMap(\.declaration)) == bySectionDeclarations)
        #expect(inBinaryOrder.declarationPieces.allSatisfy { $0.declaration != nil })
    }

    @Test("The header is no declaration")
    func headerIsNoDeclaration() async throws {
        let output = DeclarationRecordingOutput()
        try await DumpRequest(source: Self.fixture, sections: .only([.protocols]), emitsHeader: true).run(output: output, environment: .testing)

        let firstPiece = try #require(output.declarationPieces.first)
        #expect(firstPiece.declarationText?.hasPrefix("// Generated by swift-section-kit-tests 9.9.9\n") == true)
        #expect(firstPiece.declaration == nil)
        #expect(output.declarationPieces.dropFirst().allSatisfy { $0.declaration != nil })
    }

    // MARK: - interface

    @Test("Interface progress is three steps, and the interface is one piece")
    func interfaceProgressWithoutHeader() async throws {
        let output = RecordingOutput()
        try await InterfaceRequest(source: Self.fixture).run(output: output, environment: .testing)

        #expect(output.messages(of: .progress) == [
            "Preparing to build Swift interface...",
            "Building Swift interface...",
            "Swift interface built successfully.",
        ])
        #expect(output.products.count == 1)
        #expect(output.indexingLabels == [nil])
    }

    /// With a header, "Preparing…" is announced before the header's symbol
    /// index build rather than after it, so nothing is heard for the whole
    /// build otherwise.
    @Test("With a header and a file, the file holds what would have been printed, minus the final newline")
    func interfaceWithHeaderToFile() async throws {
        let directoryURL = try FixtureFiles.makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directoryURL) }
        let interfacePath = directoryURL.appendingPathComponent("SymbolTestsCore.swiftinterface").path

        let printed = RecordingOutput()
        try await InterfaceRequest(source: Self.fixture, emitsHeader: true).run(output: printed, environment: .testing)
        let written = RecordingOutput()
        try await InterfaceRequest(source: Self.fixture, emitsHeader: true, destination: .file(path: interfacePath))
            .run(output: written, environment: .testing)

        #expect(written.products.isEmpty)
        #expect(written.messages(of: .progress) == [
            "Preparing to build Swift interface...",
            "Building Swift interface...",
            "Swift interface built successfully.",
            "Writing Swift interface to \(interfacePath)...",
        ])
        let fileContents = try String(contentsOfFile: interfacePath, encoding: .utf8)
        #expect(fileContents + "\n" == printed.printedProduct)
        #expect(fileContents.hasPrefix("// Generated by swift-section-kit-tests 9.9.9\n"))
    }
}
