name: macOS 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos_test:
    name: Execute tests on macOS
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
        xcode-version: ["16.3"]
        release: [2024]
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Swift version
        run: swift --version
      - name: Build and run tests in debug mode
        run: |
          swift test \
            -c debug \
            --build-path .build-test-debug
      - name: Build and run tests in release mode
        run: |
          swift test \
            -c release \
            --build-path .build-test-release
